### ISSUE TITLE
Meta question raised by Adrian: Should the schedule model be moved out into a seperate document?

### ISSUE THREAD

**Issue by QiufangMa** [boucadair/policy-based-network-acl#17]
There is a meta-question: should the schedule model be moved out into a separate document? It isn't necessary at this point in time (we can continue to work on everything in one document), but given the intended wider applicability it might be convenient to hold it in a separate document.

**Comment by boucadair** [comment]
I also received the same comment from Victor Lopez (Nokia).  

@QiufangMa, I suggest that you start a thread in the mailing list for this issue. The sooner we have guidance from the WG, the better. Thanks.
