### ISSUE TITLE
PEPs to be group-aware 

### ISSUE THREAD

**Issue by boucadair** [boucadair/policy-based-network-acl#57]
We do have the following:

> In some cases, a PEP may map incoming packets to their associated source or destination endpoint-group IDs, and acts on the endpoint-group ID based ACL policies, e.g., a NAS as the PEP or a group identifier could be carried in packet header (see [Section 6.2.3](https://datatracker.ietf.org/doc/html/draft-ietf-nvo3-encap-11#section-6.2.3) of [[I-D.ietf-nvo3-encap](https://boucadair.github.io/policy-based-network-acl/draft-ietf-opsawg-ucl-acl.html#I-D.ietf-nvo3-encap)]).

I thought we agreed to leave the mapping to encap proto out of scope. If so, do we need to maintain the above text?

**Comment by QiufangMa** [comment]
The quoted text is okay for me to keep, we leave the mapping mechanism out of scope, but IMHO we can still treat the identifier being encapsulated as an option.
