### ISSUE TITLE
Should the "basic-recurrence-supported" and "icalendar-recurrence-supported" be defined as dependent or mutually exclusive?

### ISSUE THREAD

**Issue by QiufangMa** [boucadair/policy-based-network-acl#63]
Appendix B.1 defines two recurrence container, one for basic recurrence, and the other for icalendar recurrence, with different if-feature dedefined inside the containers, respectively. This is with the expection that "basic-recurrence-supported" and "icalendar-recurrence-supported" would not be declared by implementations at the same time, otherwise there would be redundancy. I am wondering if this is the right way to handle？

**Comment by QiufangMa** [comment]
thank you Med, works for me.

**Comment by boucadair** [comment]
Fixed in https://github.com/boucadair/policy-based-network-acl/pull/65
