### ISSUE TITLE
list endpoint-groups under acls

### ISSUE THREAD

**Issue by boucadair** [boucadair/policy-based-network-acl#66]
https://github.com/boucadair/policy-based-network-acl/blob/7e8cacbfefc260b496a3cdb5674bdfef6065df40/yang/ietf-ucl-acl.yang#L247

endpoint-groups should be independent of a given ACL entry, and as such should be listed directly under "acls":

> OLD:
>   augment /acl:acls/acl:acl:
>     +--rw endpoint-groups
>        +--rw endpoint-group* [group-id]
>           +--rw group-id      string
>           +--rw group-type?   identityref
> 
> NEW:
>   augment /acl:acls:
>     +--rw endpoint-groups
>        +--rw endpoint-group* [group-id]
>           +--rw group-id      string
>           +--rw group-type?   identityref

The change will also help clarify the unicity scope of group-id (all ACLs):

>         leaf group-id {
>           type string {
>             length "1..64";
>           }
>           description
>             "The endpoint group identifier that uniquely identifies
>              an endpoint group.";

**Comment by QiufangMa** [comment]
agree, endpont-group should be global. I will fix this.
