### ISSUE TITLE
Change of affiliation 

### ISSUE THREAD

**Issue by danielkinguk** [boucadair/policy-based-network-acl#7]
Folks, if there is no objection I would like to use my Lancaster affiliation in the next version of the document. 

Daniel King 
Lancaster University
d.king@lancaster.ac.uk

As we will be implementing the model as part of a new project TUDOR:

https://www.lancaster.ac.uk/dsi/about-us/news/new-12m-project-to-make-future-telecommunications-network-greener-more-resilient-and-ubiquitous

A key component of the project is scheduled access control to resources. I am leading some of the management and control plane work on TUDOR and will be using ETSI TFS (an SDN Controller I helped develop in the EC project TERAFLOW) and a RADIUS server to manage authentication and authorisation. This I-D will be implemented and tested, so I'll have some implementation feedback in the near future.

**Comment by QiufangMa** [comment]
Sure, just update your affiliation whenever you like, but be aware that the submission window will be closed next Monday. So happy to know that you will be implementing this draft, that's a very exciting news! Looking forward to your implementation feedback;-)

**Comment by danielkinguk** [comment]
Thanks! I will also present the I-D on the next ETSI TFS call. I will be keen to see if any of the TeraFlow vendor partners will support the work.
