### ISSUE TITLE
(Luis) Issue #1 for draft-ma-opsawg-schedule-yang – Reference to RFC3339 should be added

### ISSUE THREAD

**Issue by luismcontreras** [boucadair/policy-based-network-acl#73]
Missing reference to RFC3339 regarding the expression of dates and time.

**Comment by boucadair** [comment]
Not sure if we need this one as we are leverage date-and-time (from rfc6991, which already refers to RFC3339).

**Comment by QiufangMa** [comment]
I tend to agree with Med, the description of typedef "date-and-time" already refers to RFC3339.
Maybe we can add something in the draft like :
   "XXX uses 'date-and-time' type defined in I-D.ietf-netmod-rfc6991-bis which
   conforms to the representation format in section 5.6 of RFC3339."
But I don't feel that necessary, thoughts?

**Comment by luismcontreras** [comment]
Maybe referencing RFC 6991 bis would be sufficient, which by the way is not included as reference.

**Comment by boucadair** [comment]
> Maybe referencing RFC 6991 bis would be sufficient, which by the way is not included as reference.

It is cited in Section 5:

"This module imports types defined in [[I-D.ietf-netmod-rfc6991-bis](https://boucadair.github.io/policy-based-network-acl/draft-ma-opsawg-schedule-yang.html#I-D.ietf-netmod-rfc6991-bis)]."

**Comment by QiufangMa** [comment]
Close this issue as RFC 6991 is referenced normatively.
