### ISSUE TITLE
(Luis) Issue #4 for draft-ma-opsawg-schedule-yang – Security considerations

### ISSUE THREAD

**Issue by luismcontreras** [boucadair/policy-based-network-acl#76]
The current content of the section is fine for the protocol mechanism. But there is no mention to risks due to the parameters use din the schedule. I suggest to create a section 6.1 with current content and a section 6.2 referring to data in the schedule.
Regarding that section, the following could reflect the risks I’m referring to:
8< --
Improper values in the schedule could be leveraged for creating attacks such as denial of service. Those improper values refer to:
-	Use a past ending time with relation to the indicated starting time
-	Use a non-valid combination of day and month (e.g. September 31st)
-	Use of value February 29th for a non leap-year
Furthermore, very often and very close schedules can be an additional source of attacks by keeping the system permanently busy with the management of the schedules.
Finally, schedules received with an starting time in the past with respect to current time should be discarded.
8< --

**Comment by boucadair** [comment]
Technically speaking, we don't expose any data node in the common model but I think it is good to list the items you provided to illustrate misuses.

It would be better to include guards in the model itself to avoid some of these.

**Comment by QiufangMa** [comment]
Yes, I agree this should be added. and these considerations would be for the designers of other modules which uses this common schedule yang module. 

Though I appreciate the idea to guard the usage of it in the model itself, I guess it is not going to be easy, e.g., how to forbid a use of value February 29th for a non leap-year in the following date-and-time string "pattern" statement:         
pattern '[0-9]{4}-(1[0-2]|0[1-9])-(0[1-9]|[1-2][0-9]|3[0-1])'
               + 'T(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?'
               + '(Z|[\+\-]((1[0-3]|0[0-9]):([0-5][0-9])|14:00))?'

**Comment by QiufangMa** [comment]
I think some considerations here are not really related to the security, see if the added sec works: https://boucadair.github.io/policy-based-network-acl/draft-ma-opsawg-schedule-yang.html#section-5
Feel free to propose text or issue PR if needed.

**Comment by QiufangMa** [comment]
Close this issue as a new section is added to take care of this.
